var N = null;var sourcesIndex = {};
sourcesIndex["aoc"] = {"name":"","dirs":[{"name":"files","files":["mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["d01"] = {"name":"","files":["main.rs"]};
sourcesIndex["d02"] = {"name":"","files":["main.rs"]};
sourcesIndex["d03"] = {"name":"","files":["main.rs"]};
sourcesIndex["d04"] = {"name":"","files":["main.rs"]};
sourcesIndex["d05"] = {"name":"","files":["main.rs"]};
sourcesIndex["d06"] = {"name":"","files":["main.rs"]};
sourcesIndex["d07"] = {"name":"","files":["main.rs"]};
sourcesIndex["d08"] = {"name":"","files":["main.rs"]};
sourcesIndex["d09"] = {"name":"","files":["main.rs"]};
sourcesIndex["d10"] = {"name":"","files":["main.rs"]};
sourcesIndex["d11"] = {"name":"","files":["main.rs"]};
createSourceSidebar();
