[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
description = "Utility functions and macros for reuse in AoC 2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[dev-dependencies]
tempfile = "3"
